# Setup
title:            Rafael Pierre
tagline:          'Solutions Architect & Machine Learning Engineer'
description:      'Random Data, AI, ML and MLOps thoughts, ramblings and whatnot.'
url:              https://rafaelpierre.github.io
baseurl:          ''
paginate:         5
github_username: rafaelpierre
github_repo: "rafaelpierre"

# About and contact
author:
  name:           'Rafael Pierre'
  url:            https://www.medium.com/@rafaelpierre

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

theme: 

markdown: kramdown
highlighter: rouge


# Custom vars
version:          3.0.0
