# Setup
title:            Rafael Pierre
tagline:          'Solutions Architect & Machine Learning Engineer'
description:      'Random Data, AI, ML and MLOps thoughts, ramblings and whatnot.'
url:              https://rafaelpierre.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Rafael Pierre'
  url:            https://www.medium.com/@rafaelpierre

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

# Custom vars
version:          3.0.0
